spring.application.name: gateway
server.port: 8000

management:
  endpoint.gateway.enabled: true
  endpoints.web.exposure.include: gateway

spring:
  security.oauth2:
    client:
      provider.techstructure-keycloak:
        issuer-uri: "http://authorization-keycloak:8080/realms/Techstructure"
      registration.techstructure-keycloak:
        redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
        client-id: wearecooking-gateway
        client-secret: CDh0LN1ZDRziVB66ZApYZJOq20ETNJw7
        provider: techstructure-keycloak
        authorization-grant-type: authorization_code
        scope: openid,profile,email
  cloud:
    gateway:
      routes:
        - id: test
          uri: "http://localhost:8030"
          predicates:
            - Path=/test/**
        #          filters:
        #            - AuthFilter
        - id: userinfo
          uri: "http://localhost:8031"
          predicates:
            - Path=/api/userinfo/**
#        - id: <name>
#          uri: "http://localhost:<host port in .env>"
#          predicates:
#            - Path=/api/<abc>/**