databaseChangeLog:
  - changeSet:
      id: 2025-05-17-2000-remove-id-from-user-profiles
      author: technosudo
      changes:
        - dropColumn:
            tableName: user_profiles
            columnName: user_id
        - dropColumn:
            tableName: user_profiles
            columnName: id
        - addColumn:
            tableName: user_profiles
            columns:
              - column:
                  name: user_uuid
                  type: UUID
        - addPrimaryKey:
            tableName: user_profiles
            columnNames: user_uuid
