databaseChangeLog:
- changeSet:
    id: add-quantity-fridge-ingredients
    author: czechjan
    changes:
    
        - createTable:
            tableName: units
            columns:
                - column: { name: id, type: uuid, constraints: { primaryKey: true, nullable: false }, defaultValueComputed: gen_random_uuid() }
                - column: { name: name, type: varchar(100) }
        
        - createTable:
            tableName: ingredient_units_ratios
            columns:
                - column: { name: ingredient_id, type: uuid, constraints: { primaryKey: true, nullable: false } }
                - column: { name: unit_one_id, type: uuid, constraints: { primaryKey: true, nullable: false } }
                - column: { name: unit_two_id, type: uuid, constraints: { primaryKey: true, nullable: false } }
                - column: { name: one_to_two_ratio, type: double, constraints: { nullable: false }}
    
        - addColumn:
            tableName: user_fridge_ingredients
            columns:
                - column:
                    name: quantity
                    type: double
                    constraints:
                        nullable: false
                - column:
                    name: unit_id
                    type: uuid
                    constraints:
                        nullable: false
                        
        - addColumn:
            tableName: recipe_ingredients
            columns:
                - column:
                    name: quantity
                    type: double
                    constraints:
                        nullable: false
                - column:
                    name: unit_id
                    type: uuid
                    constraints:
                        nullable: false
       
        - addForeignKeyConstraint:
            constraintName: fk_fridge_ingredient_unit
            baseTableName: user_fridge_ingredients
            baseColumnNames: unit_id
            referencedTableName: units
            referencedColumnNames: id

        - addForeignKeyConstraint:
            constraintName: fk_recipe_ingredient_unit
            baseTableName: recipe_ingredients
            baseColumnNames: unit_id
            referencedTableName: units
            referencedColumnNames: id

        - addForeignKeyConstraint:
            constraintName: fk_ingredient_unit_ratio_ing
            baseTableName: ingredient_units_ratios
            baseColumnNames: ingredient_id
            referencedTableName: ingredients
            referencedColumnNames: id

        - addForeignKeyConstraint:
            constraintName: fk_ingredient_unit_ratio_uone
            baseTableName: ingredient_units_ratios
            baseColumnNames: unit_two_id
            referencedTableName: units
            referencedColumnNames: id

        - addForeignKeyConstraint:
            constraintName: fk_ingredient_unit_ratio_utwo
            baseTableName: ingredient_units_ratios
            baseColumnNames: unit_two_id
            referencedTableName: units
            referencedColumnNames: id