services:
  wrc-db:
    container_name: "wrc-db"
    image: postgres:17
    ports:
      - "$WRC_DB:5432"
    environment:
      POSTGRES_DB: wrc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./db-volumes/wrc:/var/lib/postgresql/data
    networks:
      - wrcNetwork

  wrc-liquibase-db-main:
    container_name: "wrc-liquibase-db-main"
    image: liquibase/liquibase:4.25
    command: update
    environment:
      LIQUIBASE_COMMAND_DRIVER: org.postgresql.Driver
      LIQUIBASE_COMMAND_URL: jdbc:postgresql://wrc-db:5432/wrc
      LIQUIBASE_COMMAND_USERNAME: admin
      LIQUIBASE_COMMAND_PASSWORD: admin
      LIQUIBASE_COMMAND_CHANGELOG_FILE: db.changelog.yaml
      LIQUIBASE_SEARCH_PATH: /liquibase/changelog
    depends_on:
      - wrc-db
    volumes:
      - ./liquibase/main-db/changelog:/liquibase/changelog
    networks:
      - wrcNetwork

networks:
  wrcNetwork:
    name: wrcNetwork
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
