services:
  wrc-db:
    container_name: "wrc-db"
    image: postgres:17
    ports:
      - "$WRC_DB:5432"
    environment:
      POSTGRES_DB: wrc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./wrc-db-data:/var/lib/postgresql/data
    networks:
      - wrcNetwork

  wrc-liquibase-db-main:
    container_name: "wrc-liquibase-db-main"
    build:
      context: ../services/liquibase/main-db
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://wrc-db:5432/wrc
      DB_USER: admin
      DB_PASSWORD: admin
    depends_on:
      - wrc-db
    networks:
      - wrcNetwork

networks:
  wrcNetwork:
    name: wrcNetwork
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.2.0/24
