version: "3.9"

services:
  recommender:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MOCK_DATA_PATH=./mock_data/
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_DB=0
    depends_on:
      - redis
    volumes:
      - ./mock_data:/app/mock_data

  redis:
    image: redis:7
    ports:
      - "6379:6379"